pom.xml
src/main/java/propensi/d06/sihedes/security/WebSecurityConfig.java
src/main/resources/templates/fragments/fragment.html

1. [x] Does your submission pass tests?
2. [x] Is the feature has been locally tested?

feat : authorization navbar

---

src/main/java/propensi/d06/sihedes/controller/SLAController.java
src/main/java/propensi/d06/sihedes/controller/TicketController.java
src/main/java/propensi/d06/sihedes/controller/UserController.java
src/main/java/propensi/d06/sihedes/repository/UserDb.java
src/main/java/propensi/d06/sihedes/service/UserService.java
src/main/java/propensi/d06/sihedes/service/UserServiceImpl.java
src/main/resources/static/css/fragment.css
src/main/resources/templates/change_pass.html
src/main/resources/templates/daftar-sla.html
src/main/resources/templates/fragments/fragment.html
src/main/resources/templates/myTickets.html
src/main/resources/templates/pendingTickets.html
src/main/resources/templates/profil.html

refactor : fe Profile and password

---

src/main/resources/static/css/error.css
src/main/resources/templates/error/404.html

1. [x] Does your submission pass tests?
2. [x] Is the feature has been locally tested?

error page : 404

---

src/main/resources/templates/error/400.html
src/main/resources/templates/error/403.html
src/main/resources/templates/error/500.html

adding error pages

---

src/main/java/META-INF/MANIFEST.MF
src/main/java/propensi/d06/sihedes/controller/TicketController.java
src/main/resources/templates/createRequest.html

refactor: SLM, all tickets and pending ticket logic

---

src/main/java/propensi/d06/sihedes/controller/SLAController.java

fix: fix sla boa assign

---

src/main/resources/templates/daftar-sla.html
src/main/resources/templates/form-add-sla.html

1. [x] Does your submission pass tests?
2. [x] Is the feature has been locally tested?

fix : UI Service Catalog

---

src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java

fix: fix id approver

---

src/main/java/propensi/d06/sihedes/controller/TicketController.java

refactor: change pending ticket content

---

src/main/java/propensi/d06/sihedes/controller/TicketController.java

fix: fix ticket

---

src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java

fix: fix approval

---

src/main/resources/templates/detailRequestApproval.html

1. [x] Does your submission pass tests?
2. [x] Is the feature has been locally tested?

fix : approver notif

---

src/main/java/propensi/d06/sihedes/controller/TicketController.java
src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java

Fix: feedback rejected request

---

src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java

Fix: feedback when request rejected

---

src/main/java/propensi/d06/sihedes/controller/PageController.java
src/main/java/propensi/d06/sihedes/controller/RequestExcelExporter.java
src/main/java/propensi/d06/sihedes/controller/TicketController.java
src/main/java/propensi/d06/sihedes/model/ProblemModel.java
src/main/java/propensi/d06/sihedes/model/RequestModel.java
src/main/java/propensi/d06/sihedes/repository/ProblemDb.java
src/main/java/propensi/d06/sihedes/repository/RequestDb.java
src/main/java/propensi/d06/sihedes/service/ProblemService.java
src/main/java/propensi/d06/sihedes/service/ProblemServiceImpl.java
src/main/java/propensi/d06/sihedes/service/RequestService.java
src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java
src/main/resources/templates/allTickets.html
src/main/resources/templates/detail-vendor.html
src/main/resources/templates/detailRequest.html
src/main/resources/templates/detailRequestApproval.html
src/main/resources/templates/home.html
src/main/resources/templates/individual-request.html
src/main/resources/templates/myTickets.html
src/main/resources/templates/pendingTickets.html

Dashboard with visualization

---

src/main/resources/templates/createRequest.html
src/main/resources/templates/detailRequestApproval.html

Fix: minor html changes

---

src/main/java/propensi/d06/sihedes/controller/PageController.java
src/main/java/propensi/d06/sihedes/repository/ProblemDb.java
src/main/java/propensi/d06/sihedes/service/ProblemService.java
src/main/java/propensi/d06/sihedes/service/ProblemServiceImpl.java
src/main/java/propensi/d06/sihedes/service/RequestService.java
src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java
src/main/resources/templates/home.html

feat: graph for front page

---

src/main/java/propensi/d06/sihedes/controller/PageController.java
src/main/java/propensi/d06/sihedes/service/ProblemServiceImpl.java
src/main/java/propensi/d06/sihedes/service/RequestServiceImpl.java

refactor: change logic to graphic

---

src/main/resources/templates/daftar-sla.html
src/main/resources/templates/knowledge-base.html
src/main/resources/templates/vendorRequest.html

fix: fix delete KB

---

src/main/resources/templates/vendorProblem.html

refactor: change modal problem vendor
